### ISSUE TITLE
Team photo alt text repetative for screen reader

### ISSUE THREAD

**Issue by LeeJMorel** [uwcse440/web-cse440-24wi#36]
Screen readers identify objects as images, and this reuses elements already read and described in the title in addition to labeling it as a photo. For example, if I use windows narrator to navigate this page it will say:

Team -> Person1 -> Photo of Team Person1.image

This does not provide new information to the person navigating with a screen reader, [harvard](https://accessibility.huit.harvard.edu/describe-content-images) provides a short list of convention to follow to write good alt text.

  -  Add alt text all non-decorative images.
  -  Keep it short and descriptive, like a tweet.
  -  Don’t include “image of” or “photo of”.
  -  Leave alt text blank if the image is purely decorative
  -  It's not necessary to add text in the Title field. 
  
  A simple solution you might consider that aligns with [W3C access guidelines](https://www.w3.org/WAI/tutorials/images/informative/) is simply labeling these images as "decorative" since they are not meant to convey much additional information.

``` {/* The ProjectTeamGallery displays names and images of your project team.
  * - As above, crop and scale your images to be the size of the placeholder.
  *   This consistent image size provides a cleaner gallery.
  */}
<ProjectTeamGallery members={[
    {
        name: ["Team", "Person 1"],
        photo: imageTeamPerson1,
        // A default alt of "Photo of Team Person 1." will be generated.
    },
    {
        name: ["Team", "Person 2"],
        photo: imageTeamPerson2,
        // A default alt of "Photo of Team Person 3." will be generated.
    },
    {
        name: ["Team", "Person 3"],
        photo: imageTeamPerson3,
        // A default alt of "Photo of Team Person 3." will be generated.
    },
    {
        name: ["Team", "Person 4"],
        photo: imageTeamPerson4,
        alt: "Photo of Team Person 4, looking cool with their additional image description."
    },
]} /> ```

**Comment by jayfo** [comment]
Thanks for this @LeeJMorel! And fixing it in the components/template should carry forward year over year.

- Easy for me to 100% agree that any default text should not include "Photo of".

- I also see that repeating is bad, so that probably cuts out default text completely.

- I'm struggling more with no description at all. Alt text for images of people is a big open thing, especially if those images are serving as introductions (e.g., allowing people to describe themselves). So they're not simply "decorative", but there's also a variety of approaches to this.

I'm converging more toward:

- Make the alt tag optional (i.e., problematic in its own way, but perhaps ok in combination with the rest of this).
- If there is an alt tag, use it.
- Otherwise mark the image decorative.

Does that seem to thread the needle for you?
